version: 4.10.{build}
skip_tags: true
environment:
  BUILD_TYPE: Release
  ARCH: x64
  matrix:
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2019
    GENERATOR: Visual Studio 16 2019
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2017
    GENERATOR: Visual Studio 15 2017
  - APPVEYOR_BUILD_WORKER_IMAGE: Visual Studio 2015
    GENERATOR: Visual Studio 14 2015
matrix:
  fast_finish: true
build_script:
- cmd: >-
    cd %APPVEYOR_BUILD_FOLDER%


    mkdir build


    cd build


    dir


    cmake -S ../vstgui/ -B . -G"%GENERATOR%" -A %ARCH%


    dir


    cmake --build . --config %BUILD_TYPE%